name = "my-nextjs-app"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

# ระบุตำแหน่งไฟล์หลักที่ได้จากการบิลด์ของ OpenNext
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"